;=====================================================
;
; To learn more about how to configure Polybar
; go to https://github.com/jaagr/polybar
;
; The README contains a lot of information
;
; Themes : https://github.com/jaagr/dots/tree/master/.local/etc/themer/themes
; https://github.com/jaagr/polybar/wiki/
; https://github.com/jaagr/polybar/wiki/Configuration
; https://github.com/jaagr/polybar/wiki/Formatting
;
;=====================================================
[global/wm]
;https://github.com/jaagr/polybar/wiki/Configuration#global-wm-settings
margin-top = 0
margin-bottom = 0

[settings]
;https://github.com/jaagr/polybar/wiki/Configuration#application-settings
throttle-output = 5
throttle-output-for = 10
screenchange-reload = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
; Define fallback values used by all module formats
format-foreground = #f3f4f5
format-background = #aa000000

